---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: fdbserver --version
    register: fdb_test_output
  - name: fdbserver --version
    debug:
      msg: '{{ fdb_test_output.stdout }}'
