---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: looking for install in {{ fdb_install_dir }}
  become: yes
  stat:
    path: '{{ fdb_install_dir }}'
  changed_when: False
  register: fdb_bin_dir
- when: not fdb_bin_dir.stat.exists
  block:
    - name: downloading {{ fdb_tgz_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ fdb_tgz_url }}'
        dest: '{{ fdb_tmp_tgz }}'
        checksum: '{{ fdb_checksum }}'
        mode: 0644
    - name: mkdir {{ fdb_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ fdb_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ fdb_tmp_tgz }} into {{ fdb_install_dir }}
      become: yes
      become_user: root
      unarchive:
        src: '{{ fdb_tmp_tgz }}'
        dest: '{{ fdb_install_dir }}'
        mode: 0755
        creates: '{{ fdb_install_dir }}/fdb_binaries'
  always:
    - name: rm {{ fdb_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ fdb_tmp_tgz }}'
        state: absent
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ fdb_install_dir }}'
    dest: '{{ fdb_link_dir }}'
    state: link
- name: add to login shell path
  become: yes
  become_user: root
  with_items:
    - d: /etc/profile.d
      f: fdb.sh
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
    
